name: Daily Git Summary

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get full diff from last 24h
        run: |
          git fetch origin
          git log --since="24 hours ago" --pretty=format:"%H" > commit_hashes.txt
          > diff.txt
          while read hash; do
            git show $hash --no-color --unified=0 >> diff.txt
            echo -e "\n\n" >> diff.txt
          done < commit_hashes.txt

          echo "DIFF_CONTENT<<EOF" >> $GITHUB_ENV
          cat diff.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          CONTENT=$(echo "${DIFF_CONTENT}" | head -c 12000 | sed 's/"/\\"/g')
          echo '{
            "model": "gpt-4",
            "messages": [
              {"role": "system", "content": "Jesteś doświadczonym architektem Java Spring. Podsumuj zmiany kodu z ostatnich 24h. Zorganizuj je według warstw aplikacji (kontrolery, serwisy, repozytoria, modele, konfiguracja, testy itd.). Uwzględnij istotne zmiany techniczne."},
              {"role": "user", "content": "'"$CONTENT"'"}
            ]
          }' > payload.json

          curl https://api.openai.com/v1/chat/completions \
            -s \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d @payload.json \
            > summary.json

      - name: Show summary
        run: jq -r '.choices[0].message.content' summary.json
